### ISSUE TITLE
Redirection auto ?

### ISSUE THREAD

**Issue by romsworld** [Qarj/WebInject#18]
Hi,

How is managed 302. Is automatic redirection ? Or is it possible with an option ?

Thanks,

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>

<h1>Found</h1>

<p>The document has moved <a href="https://url/portail">here</a>.</p>

</body></html>

**Comment by Qarj** [comment]
WebInject does not follow redirects, you need to follow them manually

So in the step returning the 302, you would parse off the redirect location

```
    parseresponseREDIRECTURL="Location: |\n|decode"
```

Then in the next step you just GET that URL. You do need to know though if it is an absolute URL or relative:

If absolute

```
    url="{REDIRECTURL}"
```

If relative and not https:

```
    url="http://www.example.com{REDIRECTURL}"
```

**Comment by romsworld** [comment]
Ok, so is manual.

Is it possible to put as option in config file the max redirect ?

**Comment by Qarj** [comment]
It would be possible, I've thought about doing it a number of times, but never have since we don't really need it and in fact it is good to write deterministic tests so that a given action is expected to redirect an exact number of times. If that ever changes, then we investigate why since that might indicate an issue.

Lets leave this open, I might implement that feature when I get time, but if I do, I will probably see if I can put it on the actual test step so it will be valid for that test step only, meaning that it will be possible to have a different max_redirect per test step instead of the entire test suite. Also, I would want it to be obvious to someone else who is reading the test script to be aware of what is going on.

**Comment by Qarj** [comment]
A maxredirect parameter has been added that will affect GET requests only. Read about it in the manual.

**Comment by romsworld** [comment]
Thanks,

But perhaps, I don’t understand some thing,
Where can I put maxredirect parameter ? I added it in test.xml in step directly, but I have an error.

./webinject.pl -c test-config.xml
Can't call method "max_redirect" on an undefined value at ./webinject.pl line 315.

Test-config.xml

<root>
    <testcasefile>test.xml</testcasefile>
    <useragent>Mozilla/5.0 (Windows NT 6.3; Trident/7.0; rv:11.0) like Gecko</useragent>
    <globalretry>20</globalretry> 
    <reporttype>standard</reporttype>
</root>

Test.xml

<testcases repeat="1">

<case
    id="20"
    description1="Get home page"
    method="get"
    url="http://google.fr"
    maxredirect="5"
/>

</testcases>

**Comment by Qarj** [comment]
You found a bug - it does not work on the very first test step.

Hopefully this is now fixed - give it a go and let me know. (I've tested this scenario, so it should work)

**Comment by romsworld** [comment]
Excellent, it works !

Thanks,
