### ISSUE TITLE
Page zip

### ISSUE THREAD

**Issue by gildasiosousa** [Qarj/WebInject#51]

**Comment by gildasiosousa** [comment]
We are using webinject test case for an url that runs on a apache server with gzip enabled. Verifiy positive fails due to gzip encode. Please let us know how we can do verifypositive on a compressed content.

**Comment by Qarj** [comment]
Is there an example server on the open internet where this happens? It isn't a problem I have ever seen. What OS and version of Perl are you using? Are you seeing warning messages in the test output to the console?

Do you get the problem for https://www.totaljobs.com ? It has gzip enabled, but it works fine for me.

**Comment by gildasiosousa** [comment]
Hi @Qarj 
System operation is CentOs 7. This is perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi.
The problem occurs in the login to the page, after the verification of the login, I can not verify the strigns of the page (verifypositive: briefcase).

Here is an example of my script to check.
step:            Get the login page
desc:            Check page is available
url:                https://myapplication
verifypositive:   login
verifycode:       200
sleep:            	3

step:             Submit Login details
desc:             login sucess
url:                https://myapplication
method:        put
posttype:      application/x-www-form-urlencoded
postbody:     user=admin&password=123456
verifycode:   303
verifypositive: briefcase


Thank you!

**Comment by Qarj** [comment]
I'm a little surprised you are using method `put`, for logins `post` is the standard since you are creating a login session according to REST principles - or so I'm told.

Note that you need use `verifyresponsecode` instead of `verifycode`.

```
step:                   Get the login page
desc:                   Check page is available
url:                    https://myapplication
verifypositive:         login
verifyresponsecode:     200
sleep:                  3

step:                   Submit Login details
desc:                   login success
url:                    https://myapplication
method:                 put
posttype:               application/x-www-form-urlencoded
postbody:               user=admin&password=123456
verifyresponsecode:     303
verifypositive:         briefcase
```

I know people have had some problems installing all the correct Perl packages with CentOs 7. If you run the self test do you get any errors?

```
perl wi.pl selftest/all_core.test
```

**Comment by gildasiosousa** [comment]
The truth is that the put method is wrong.
I execute the perl wi.pl selftest/all_core.test perl command and it did not show any errors, passed all steps.

**Comment by Qarj** [comment]
I'm getting a lot of errors with the self test on CentOs 7 - mainly because I can't get `LWP:Protocol::https` to install. I thought I'd managed it once before but now I can't do it. I'm not familiar with CentOs. Do you have any tips for installing it? If so I'll update my instructions, and I'll investigate your problem further.

When running `sudo cpan LWP::Protocol::https`

I get the output:
```
Test Summary Report
-------------------
t/https_proxy.t (Wstat: 5120 Tests: 56 Failed: 20)
  Failed tests:  37-56
  Non-zero exit status: 20
Files=2, Tests=61,  2 wallclock secs ( 0.04 usr  0.00 sys +  0.70 cusr  0.09 csys =  0.83 CPU)
Result: FAIL
Failed 1/2 test programs. 20/61 subtests failed.
make: *** [test_dynamic] Error 20
  OALDERS/LWP-Protocol-https-6.07.tar.gz
  /bin/make test -- NOT OK
//hint// to see the cpan-testers results for installing this module, try:
  reports OALDERS/LWP-Protocol-https-6.07.tar.gz
```

Note that if you got all the self tests to pass then gzip should be working fine since https://www.totaljobs.com uses gzip and one of the self tests calls it.

**Comment by Qarj** [comment]
I've now got all the self tests to pass, I kept on installing packages until it worked.

```
sudo yum install perl-Crypt-SSLeay
sudo yum install perl-LWP-Protocol-https
sudo yum groupinstall "Development Tools"
sudo yum install openssl-devel
```

The next challenge is to try and recreate your error. It would be good if you can post the Response Headers and any error output that might give some clue (i.e. the content of `output/20.html`)

**Comment by Qarj** [comment]
Ok, it looks like I've recreated the error with this test:

```
step:           Get a gzip page
url:            https://varvy.com/pagespeed/enable-compression.html
addheader:      Accept-Encoding: gzip
verifypositive: method of compressing
```

**Comment by gildasiosousa** [comment]
I made the installation of perl and cpan libraries, while doing the test came that result
tarting WebImblaze Engine...

Test:  testgzip.test - 10 
Get a gzip page 
Verify Positive: "method of compressing" 
Failed Positive Verification 0
Failed - No Response 
TEST STEP FAILED
Response Time = 127.499 sec 

Start Time: Fri 10 May 2019, 12:22:34
Total Run Time: 127.6 seconds

Total Response Time: 127.499 seconds

Test Steps Run: 1
Test Steps Passed: 0
Test Steps Failed: 1
Verifications Passed: 1
Verifications Failed: 2

Results at: output/Results.html

**Comment by Qarj** [comment]
I'm assuming your Apache server must have `force-gzip` enabled so it is sending gzip regardless of whether a `Accept-Encoding: gzip` header is sent or not. That is why I've never seen the problem before.

http://httpd.apache.org/docs/current/mod/mod_deflate.html

**Comment by Qarj** [comment]
Your error is a bit different to mine by the way, for me it fails instantly, it doesn't hang for 127 seconds.

I know how to fix this problem but I might not get to it for a few days since there are a lot of code changes and the risk it might create other problems so I need to do some extensive testing first. Basically instead of using `$response->content`, `$response->content_ref( )`, and `$response->as_string` I need to use `$response->decoded_content` and `$response->headers_as_string`. It isn't a simple one-to-one mapping so the code changes will need some thought.

**Comment by gildasiosousa** [comment]
OK! 
I'll wait for your fix, and think of another check on the page.
Thanks for the help and explanations.

Thank you very much!

**Comment by Qarj** [comment]
Hi @gildasiosousa 

It should work now. Please let me know.

**Comment by gildasiosousa** [comment]
Hello @Qarj 
It is possible to include the verification (strings) of pages type javascript.
posttype: text / javascript

**Comment by Qarj** [comment]
Hi @gildasiosousa I'm not sure what you mean by this since that content type is deprecated. See here: https://stackoverflow.com/questions/9664282/difference-between-application-x-javascript-and-text-javascript-content-types 

You can always add any Content-Type you want as follows:
```
addheader:    Content-Type: text/javascript
```

**Comment by gildasiosousa** [comment]
Hi @Qarj 
Thank you for your help. I managed to have good results in the verification.
Congratulations on the project!
